### ISSUE TITLE
python-caldav users are unable to create calendars

### ISSUE THREAD

**Issue by direnter** [jelmer/xandikos#101]
**Steps to Reproduce**:
```
import caldav

#url = "http://localhost:8080"
#url = "http://:@localhost:8080"
url = "http://localhost:8080/user/calendars/calendar/"

client = caldav.DAVClient(url)
principal = client.principal()
principal.make_calendar(name="Test Calendar")
```

**Expected Result**:
Calendar is created.

**Actual Result**:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/caldav/objects.py", line 324, in make_calendar
    return self.calendar_home_set.make_calendar(name, cal_id, supported_calendar_component_set=supported_calendar_component_set)
  File "/usr/lib/python3.7/site-packages/caldav/objects.py", line 335, in calendar_home_set
    chs = self.get_properties([cdav.CalendarHomeSet()])
  File "/usr/lib/python3.7/site-packages/caldav/objects.py", line 192, in get_properties
    raise Exception("The CalDAV server you are using has "
Exception: The CalDAV server you are using has a problem with path handling.
```

**Comment by jelmer** [comment]
So the issue here appears to be that python-caldav expects that the principal properties are returned with the principal having a trailing slash. 

As discussed on IRC, https://tools.ietf.org/html/rfc4918#section-5.2 requires that collection URLs end with a slash but I can't anything that suggests that principal URLs need to end with a trailing slash *or* that they should be collections (and thus have a trailing slash for that reason).

**Comment by jelmer** [comment]
So RFC 4918 (WebDAV): Section 5.2 states that collection URLs SHOULD end with a trailing slash, but this is a convention, not a hard requirement. AFAICT CalDAV doesn't add additional requirements. 

That said, xandikos does add a trailing slash now (and I believe this is fixed in python-caldav too). So I'm going to close this.
