### ISSUE TITLE
Internal server error using evolution on ios tasks

### ISSUE THREAD

**Issue by Peter4825** [jelmer/xandikos#107]
I've got a reproduceable internal server error using xandikos 0.1.0 (ac0339d35a92947b0fb72a5d05bad40402a1b81b)

How to reproduce:

1) On iOS open the Reminders app and create a reminder.  This will create the following object in your calendar:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//iOS 12.3//EN
CALSCALE:GREGORIAN
BEGIN:VTODO
CREATED:20190523T161926Z
DTSTAMP:20190523T161929Z
LAST-MODIFIED:20190523T161928Z
SEQUENCE:0
STATUS:NEEDS-ACTION
SUMMARY:Test
UID:27D8D849-8F28-45C4-961B-B4B5B745416D
X-APPLE-SORT-ORDER:580321166
END:VTODO
END:VCALENDAR
```

2) Open Evolution and refresh your calendar.  Evolution will tell you there is an internal server error during this operation.  On the server side I've got the following backtrace:
```
May 23 17:45:05 caldav-vagrant startxandikos[87]: Traceback (most recent call last):
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
May 23 17:45:05 caldav-vagrant startxandikos[87]:     self.result = application(self.environ, self.start_response)
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/web.py", line 965, in __call__
May 23 17:45:05 caldav-vagrant startxandikos[87]:     return self._inner_app(environ, start_response)
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/webdav.py", line 1801, in __call__
May 23 17:45:05 caldav-vagrant startxandikos[87]:     return do.handle(environ, start_response, self)
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/webdav.py", line 1539, in handle
May 23 17:45:05 caldav-vagrant startxandikos[87]:     app.properties, base_href, r, depth)
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/webdav.py", line 273, in wrapper
May 23 17:45:05 caldav-vagrant startxandikos[87]:     return _send_dav_responses(start_response, responses, DEFAULT_ENCODING)
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/webdav.py", line 1289, in _send_dav_responses
May 23 17:45:05 caldav-vagrant startxandikos[87]:     for response in responses:
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/caldav.py", line 482, in report
May 23 17:45:05 caldav-vagrant startxandikos[87]:     members=members):
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/webdav.py", line 1049, in traverse_resource
May 23 17:45:05 caldav-vagrant startxandikos[87]:     for (child_name, child_resource) in members(resource):
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/web.py", line 469, in calendar_query
May 23 17:45:05 caldav-vagrant startxandikos[87]:     filter=filter):
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/store/__init__.py", line 290, in _iter_with_filter_indexes
May 23 17:45:05 caldav-vagrant startxandikos[87]:     if filter.check_from_indexes(name, file_values):
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/icalendar.py", line 726, in check_from_indexes
May 23 17:45:05 caldav-vagrant startxandikos[87]:     indexes, self.tzify):
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/icalendar.py", line 544, in match_indexes
May 23 17:45:05 caldav-vagrant startxandikos[87]:     if not child.match_indexes(subindexes, tzify):
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/icalendar.py", line 540, in match_indexes
May 23 17:45:05 caldav-vagrant startxandikos[87]:     not self.time_range.match_indexes(subindexes, tzify)):
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/icalendar.py", line 410, in match_indexes
May 23 17:45:05 caldav-vagrant startxandikos[87]:     return component_handler(self.start, self.end, vs, tzify)
May 23 17:45:05 caldav-vagrant startxandikos[87]:   File "/home/vagrant/xandikos-venv/lib/python3.5/site-packages/xandikos-0.1.0-py3.5.egg/xandikos/icalendar.py", line 237, in apply_time_range_vevent
May 23 17:45:05 caldav-vagrant startxandikos[87]:     raise MissingProperty('DTSTART')
May 23 17:45:05 caldav-vagrant startxandikos[87]: xandikos.icalendar.MissingProperty: Property 'DTSTART' missing
```

**Comment by jelmer** [comment]
The odd thing here is that the crash happens for a codepath that involves a VEVENT, not a VTODO.

Are there other entries in the calendar you're encountering this for?

**Comment by jelmer** [comment]
Regardless of the cause (even if there is a client providing a bad calendar file here), Xandikos shouldn't crash.

**Comment by jelmer** [comment]
I've pushed a possible fix to master; can you please try that? It should still warn (and tell you the problematic) file when it encounters this situation.

**Comment by Peter4825** [comment]
This fix does seem to resolve it. I don't see the warning, but at least the refresh does seem to work fine.

**Comment by jelmer** [comment]
Great, thanks for confirming!
