### ISSUE TITLE
Setting the listen address results in an error

### ISSUE THREAD

**Issue by filterfish** [jelmer/xandikos#123]
If I specify the listen address to be `::0` by running:

```shell
xandikos -l ::0 --port 5232 --directory /tmp/xandikos --autocreate
```
the following stacktrace is printed:

```
Traceback (most recent call last):
  File "/usr/bin/xandikos", line 31, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/xandikos/__main__.py", line 25, in main
    return main(argv)
  File "/usr/lib/python3/dist-packages/xandikos/web.py", line 1055, in main
    server = make_server(options.listen_address, options.port, app)
  File "/usr/lib/python3.7/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno -9] Address family for hostname not supported
```

**Comment by jelmer** [comment]
This is fixed in newer versions of Xandikos, which use aiohttp rather than wsgiref to start the web server.

% ./bin/xandikos -l ::0 --port 5232 -d /tmp/xandikos --autocreate
INFO:root:Creating /tmp/xandikos/user/
INFO:root:Listening on ::0:5232
======== Running on http://[::]:5232 ========
(Press CTRL+C to quit)

**Comment by filterfish** [comment]
Wow, thank you for the incredibly quick response!
