### ISSUE TITLE
Not able to set calendar color property

### ISSUE THREAD

**Issue by barlik** [jelmer/xandikos#130]
`CalendarColorProperty.set_value` async function is never awaited in `apply_modify_prop`.

```
webdav.py:1541: RuntimeWarning: coroutine 'CalendarColorProperty.set_value' was never awaited
```

**Comment by barlik** [comment]
:open_mouth: That was quick, awesome, thank you for fixing this. :+1:

**Comment by barlik** [comment]
Getting below error with the latest code:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xandikos/webdav.py", line 2051, in handle_wsgi_request
    response = loop.run_until_complete(self._handle_request(request, environ))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/xandikos/webdav.py", line 2014, in _handle_request
    return await do.handle(request, environ, self)
  File "/usr/lib/python3.9/site-packages/xandikos/webdav.py", line 344, in wrapper
    async for resp in req_fn(self, environ, *args, **kwargs):
  File "/usr/lib/python3.9/site-packages/xandikos/webdav.py", line 1774, in handle
    propstat.extend(await apply_modify_prop(el, href, resource, app.properties))
TypeError: object async_generator can't be used in 'await' expression
```
