### ISSUE TITLE
Python 3.8: asyncio apparently missing to_thread method

### ISSUE THREAD

**Issue by tobixen** [jelmer/xandikos#211]
Here is another one ...

```
ERROR    aiohttp.server:web_protocol.py:393 Error handling request                                                                      
Traceback (most recent call last):                                                                                                      
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_protocol.py", line 422, in _handle_request                                   
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)                                                                                                       
  File "/home/tobias/caldav/tests/test_caldav.py", line 2196, in xandikos_handler                                                       
    return await mainapp.aiohttp_handler(request, "/")                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/xandikos-0.2.8-py3.8.egg/xandikos/webdav.py", line 2152, in aiohttp_handler
    response = await self._handle_request(request, environ)                                                                             
  File "/usr/local/lib/python3.8/dist-packages/xandikos-0.2.8-py3.8.egg/xandikos/webdav.py", line 2108, in _handle_request              
    return await do.handle(request, environ, self)                                                                                      
  File "/usr/local/lib/python3.8/dist-packages/xandikos-0.2.8-py3.8.egg/xandikos/webdav.py", line 1696, in handle                       
    new_etag = await r.set_body(new_contents, current_etag)                                                                             
  File "/usr/local/lib/python3.8/dist-packages/xandikos-0.2.8-py3.8.egg/xandikos/web.py", line 213, in set_body
    (name, etag) = await asyncio.to_thread(                                                                                             
AttributeError: module 'asyncio' has no attribute 'to_thread'                                                                           
```

**Comment by tobixen** [comment]
This happened while trying to do a PUT

```
self = Event(Event: http://localhost:8993/sometestuser/calendars/pythoncaldav-test/20010712T182145Z-123401%40example.com.ics)
data = 'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Example Corp.//CalDAV Client//EN\r\nBEGIN:VEVENT\r\nUID:20010712T182145Z-...714T1700
00Z\r\nDTEND:20060715T040000Z\r\nDTSTAMP:20060712T182145Z\r\nSUMMARY:foobar\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n'
id = '20010712T182145Z-123401@example.com'
path = URL(http://localhost:8993/sometestuser/calendars/pythoncaldav-test/20010712T182145Z-123401%40example.com.ics)
```

**Comment by tobixen** [comment]
Thanks, I can confirm that this solves the issue
