### ISSUE TITLE
xandikos fails to start up

### ISSUE THREAD

**Issue by tobixen** [jelmer/xandikos#213]
I have double checked that I'm on the latest revision in master (357e251d4d11e) on two boxes, one running archlinux and python 3.10, the other running ubuntu and python 3.8.  I've double checked that I've deleted everything related to xandikos and reinstalled it.  The "binary" won't start.

python 3.10:

```
$ xandikos
Traceback (most recent call last):
  File "/usr/bin/xandikos", line 33, in <module>
    sys.exit(load_entry_point('xandikos==0.2.8', 'console_scripts', 'xandikos')())
  File "/usr/bin/xandikos", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

python 3.8:

```
$ xandikos
<coroutine object main at 0x7f25919ef740>
sys:1: RuntimeWarning: coroutine 'main' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

I'll try some more bisecting again ...

**Comment by tobixen** [comment]
The "binaries" looks completely different on those two boxes.  Perhaps due to different versions of setuptools?

I need to sleep, will look more into it tomorrow.

**Comment by tobixen** [comment]
Tried installing the 0.2.8 on my laptop, here is what I got:

```
Traceback (most recent call last):
  File "/usr/bin/xandikos", line 4, in <module>
    __import__('pkg_resources').run_script('xandikos==0.2.8', 'xandikos')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/xandikos' not found in metadata at '/usr/lib/python3.10/site-packages/xandikos-0.2.8.dist-info'
```

**Comment by jelmer** [comment]
Ah, argh. Looks like we might have to go for having a sync wrapper in xandikos.__main__ after all :)
