### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe' 

### ISSUE THREAD

**Issue by mlawren** [jelmer/xandikos#226]
I'm seeing the following in Debian testing:

```
Oct 23 20:10:31 c xandikos[2994083]: ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3/dist-pa>
Oct 23 20:10:31 c xandikos[2994083]:     from markupsafe import soft_unicode
Oct 23 20:10:31 c xandikos[2994083]:   File "/usr/lib/python3/dist-packages/jinja2/filters.py", line 13, in <module>
Oct 23 20:10:31 c xandikos[2994083]:     from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
Oct 23 20:10:31 c xandikos[2994083]:   File "/usr/lib/python3/dist-packages/jinja2/defaults.py", line 3, in <module>
Oct 23 20:10:31 c xandikos[2994083]:     from .defaults import BLOCK_END_STRING
Oct 23 20:10:31 c xandikos[2994083]:   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 25, in <module>
Oct 23 20:10:31 c xandikos[2994083]:     from .environment import Environment
Oct 23 20:10:31 c xandikos[2994083]:   File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 12, in <module>
Oct 23 20:10:31 c xandikos[2994083]:     import jinja2
Oct 23 20:10:31 c xandikos[2994083]:   File "/usr/lib/python3/dist-packages/xandikos/web.py", line 30, in <module>
Oct 23 20:10:31 c xandikos[2994083]:     from .web import main
Oct 23 20:10:31 c xandikos[2994083]:   File "/usr/lib/python3/dist-packages/xandikos/__main__.py", line 26, in main
Oct 23 20:10:31 c xandikos[2994083]:     sys.exit(main(sys.argv))
Oct 23 20:10:31 c xandikos[2994083]:   File "/usr/bin/xandikos", line 31, in <module>
Oct 23 20:10:31 c xandikos[2994083]: Traceback (most recent call last):
```

I'm not sure that this is a specific xandikos error, but I vaguely think I remember you are also the Debian maintainer? Please close if this is nothing to do with xandikos...

**Comment by mlawren** [comment]
Looks like this is something kicked off by the markupsafe author (see https://github.com/pallets/markupsafe/issues/282) and the Debian jinja maintainer doesn't seem to have caught it.

Sorry for the noise.

**Comment by jelmer** [comment]
No worries :-)
