### ISSUE TITLE
git commit failed

### ISSUE THREAD

**Issue by mbauhardt** [jelmer/xandikos#82]
Hi,
I started xandikos with the `--default` option to test how xandikos works. I also used vdirsyncer to sync my calender. Furthermore I installed khal to create events. After creating an event with khal and after I called `vdirsyncer sync` the event will be uploaded successfully. But the git command fails with

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.7/site-packages/xandikos/web.py", line 935, in __call__
    return self._inner_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/xandikos/webdav.py", line 1791, in __call__
    return do.handle(environ, start_response, self)
  File "/usr/local/lib/python3.7/site-packages/xandikos/webdav.py", line 1490, in handle
    name, new_contents, content_type)
  File "/usr/local/lib/python3.7/site-packages/xandikos/web.py", line 282, in create_member
    (name, etag) = self.store.import_one(name, content_type, contents)
  File "/usr/local/lib/python3.7/site-packages/xandikos/store/git.py", line 161, in import_one
    etag = self._import_one(name, fi.normalized(), message, author=author)
  File "/usr/local/lib/python3.7/site-packages/xandikos/store/git.py", line 578, in _import_one
    author=author)
  File "/usr/local/lib/python3.7/site-packages/xandikos/store/git.py", line 550, in _commit_tree
    committer = self.repo._get_user_identity()
TypeError: _get_user_identity() missing 1 required positional argument: 'config'
127.0.0.1 - - [12/Nov/2018 21:02:09] "PUT /familie/calendars/calendar/K7HV9OHLFWNLAMCXRGTXJHCG9SFGX06EI59F.ics HTTP/1.1" 500 59
```

I created a `.git/config` directly in the collection or `.gitconfig` under my home folder. without success.
Did I missed something to configure git within xandikos? 

Any hint? 
Thx, Marko

**Comment by jelmer** [comment]
This is fixed in master; I'll try to do a release with it this week. Alternatively you can downgrade Dulwich to one or two versions earlier.

**Comment by jelmer** [comment]
0.0.11 is out now, and has the fix.
