### ISSUE TITLE
Xandikos crashes when creating calendar with DAVx (DAVDroid)

### ISSUE THREAD

**Issue by tusj** [jelmer/xandikos#93]
Summary: Running xandikos with defaults and connecting with DAVx makes xandikos give exception.

1. Initialization:
```
tusj> ~/xandikos (master=)> ./bin/xandikos --defaults -d ~/dav --dump-dav-xml -l 0.0.0.0
INFO:root:Creating /home/sindre/dav/user/
INFO:root:Create calendar in /home/sindre/dav/user/calendars/calendar.
INFO:root:Create addressbook in /home/sindre/dav/user/contacts/addressbook.
INFO:root:Create inbox in /home/sindre/dav/user/inbox.
INFO:root:Listening on 0.0.0.0:8080
```

2. Connect to running xandikos with DAVx using only the root address http://192.168.0.111:8080 makes xandikos give an exception:
```
INFO:root:Creating /home/sindre/dav/user/
INFO:root:Create calendar in /home/sindre/dav/user/calendars/calendar.
INFO:root:Create addressbook in /home/sindre/dav/user/contacts/addressbook.
INFO:root:Create inbox in /home/sindre/dav/user/inbox.
INFO:root:Listening on 0.0.0.0:8080
IN: <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><displayname /><CARD:addressbook-description /><CARD:addressbook-home-set /><current-user-principal /></prop></propfind>
OUT: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:carddav"><ns0:response><ns0:href>/</ns0:href><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype /><ns0:current-user-principal><ns0:href>/user/</ns0:href></ns0:current-user-principal></ns0:prop></ns0:propstat><ns0:propstat><ns0:status>HTTP/1.1 404 Not Found</ns0:status><ns0:prop><ns0:displayname /><ns1:addressbook-description /><ns1:addressbook-home-set /></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
192.168.0.103 - - [13/Jan/2019 20:29:28] "PROPFIND / HTTP/1.1" 207 515
192.168.0.103 - - [13/Jan/2019 20:29:28] "OPTIONS /user/ HTTP/1.1" 200 0
IN: <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><displayname /><n0:calendar-color xmlns:n0="http://apple.com/ns/ical/" /><CAL:calendar-description /><CAL:calendar-timezone /><current-user-privilege-set /><CAL:supported-calendar-component-set /><CAL:calendar-home-set /><current-user-principal /></prop></propfind>
OUT: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="http://apple.com/ns/ical/" xmlns:ns2="urn:ietf:params:xml:ns:caldav"><ns0:response><ns0:href>/</ns0:href><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype /><ns0:current-user-privilege-set><ns0:privilege><ns0:all /></ns0:privilege></ns0:current-user-privilege-set><ns0:current-user-principal><ns0:href>/user/</ns0:href></ns0:current-user-principal></ns0:prop></ns0:propstat><ns0:propstat><ns0:status>HTTP/1.1 404 Not Found</ns0:status><ns0:prop><ns0:displayname /><ns1:calendar-color /><ns2:calendar-description /><ns2:calendar-timezone /><ns2:supported-calendar-component-set /><ns2:calendar-home-set /></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
192.168.0.103 - - [13/Jan/2019 20:29:28] "PROPFIND / HTTP/1.1" 207 740
192.168.0.103 - - [13/Jan/2019 20:29:28] "OPTIONS /user/ HTTP/1.1" 200 0
IN: <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><CAL:calendar-user-address-set /></prop></propfind>
OUT: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:caldav"><ns0:response><ns0:href>/user</ns0:href><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns1:calendar-user-address-set /></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
192.168.0.103 - - [13/Jan/2019 20:29:28] "PROPFIND /user/ HTTP/1.1" 207 272
IN: <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><CARD:addressbook-home-set /><group-membership /></prop></propfind>
OUT: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:carddav"><ns0:response><ns0:href>/user</ns0:href><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns1:addressbook-home-set><ns0:href>/user/contacts/</ns0:href></ns1:addressbook-home-set><ns0:group-membership /></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
192.168.0.103 - - [13/Jan/2019 20:29:33] "PROPFIND /user/ HTTP/1.1" 207 353
IN: <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><current-user-privilege-set /><displayname /><CARD:addressbook-description /><CARD:supported-address-data /><CAL:calendar-description /><n0:calendar-color xmlns:n0="http://apple.com/ns/ical/" /><CAL:supported-calendar-component-set /><n1:source xmlns:n1="http://calendarserver.org/ns/" /></prop></propfind>
WARNING:root:Client requested unknown property {http://calendarserver.org/ns/}source
Traceback (most recent call last):
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "./bin/../xandikos/web.py", line 945, in __call__
    return self._inner_app(environ, start_response)
  File "./bin/../xandikos/webdav.py", line 1794, in __call__
    return do.handle(environ, start_response, self)
  File "./bin/../xandikos/webdav.py", line 273, in wrapper
    responses = req_fn(self, environ, *args, **kwargs)
  File "./bin/../xandikos/webdav.py", line 1559, in handle
    base_resource, base_href, depth):
  File "./bin/../xandikos/webdav.py", line 1042, in traverse_resource
    for (child_name, child_resource) in resource.members():
  File "./bin/../xandikos/web.py", line 258, in members
    ret.append((name, self._get_subcollection(name)))
  File "./bin/../xandikos/web.py", line 232, in _get_subcollection
    return self.backend.get_resource(posixpath.join(self.relpath, name))
  File "./bin/../xandikos/web.py", line 828, in get_resource
    }[store.get_type()](self, relpath, store)
  File "./bin/../xandikos/store/git.py", line 462, in get_type
    return self.config.get_type()
  File "./bin/../xandikos/store/git.py", line 217, in config
    cp.read_string(cf)
  File "/usr/lib/python3.7/configparser.py", line 721, in read_string
    sfile = io.StringIO(string)
TypeError: initial_value must be str or None, not list
192.168.0.103 - - [13/Jan/2019 20:29:33] "PROPFIND /user/contacts/ HTTP/1.1" 500 59
IN: <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><CAL:calendar-home-set /><n0:calendar-proxy-read-for xmlns:n0="http://calendarserver.org/ns/" /><n1:calendar-proxy-write-for xmlns:n1="http://calendarserver.org/ns/" /><group-membership /></prop></propfind>
OUT: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:caldav" xmlns:ns2="http://calendarserver.org/ns/"><ns0:response><ns0:href>/user</ns0:href><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns1:calendar-home-set><ns0:href>/user/calendars/</ns0:href></ns1:calendar-home-set><ns2:calendar-proxy-read-for /><ns2:calendar-proxy-write-for /><ns0:group-membership /></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
192.168.0.103 - - [13/Jan/2019 20:29:33] "PROPFIND /user/ HTTP/1.1" 207 452
IN: <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><current-user-privilege-set /><displayname /><CARD:addressbook-description /><CARD:supported-address-data /><CAL:calendar-description /><n0:calendar-color xmlns:n0="http://apple.com/ns/ical/" /><CAL:supported-calendar-component-set /><n1:source xmlns:n1="http://calendarserver.org/ns/" /></prop></propfind>
WARNING:root:Client requested unknown property {http://calendarserver.org/ns/}source
Traceback (most recent call last):
  File "/usr/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "./bin/../xandikos/web.py", line 945, in __call__
    return self._inner_app(environ, start_response)
  File "./bin/../xandikos/webdav.py", line 1794, in __call__
    return do.handle(environ, start_response, self)
  File "./bin/../xandikos/webdav.py", line 273, in wrapper
    responses = req_fn(self, environ, *args, **kwargs)
  File "./bin/../xandikos/webdav.py", line 1559, in handle
    base_resource, base_href, depth):
  File "./bin/../xandikos/webdav.py", line 1042, in traverse_resource
    for (child_name, child_resource) in resource.members():
  File "./bin/../xandikos/web.py", line 258, in members
    ret.append((name, self._get_subcollection(name)))
  File "./bin/../xandikos/web.py", line 232, in _get_subcollection
    return self.backend.get_resource(posixpath.join(self.relpath, name))
  File "./bin/../xandikos/web.py", line 828, in get_resource
    }[store.get_type()](self, relpath, store)
  File "./bin/../xandikos/store/git.py", line 462, in get_type
    return self.config.get_type()
  File "./bin/../xandikos/store/git.py", line 217, in config
    cp.read_string(cf)
  File "/usr/lib/python3.7/configparser.py", line 721, in read_string
    sfile = io.StringIO(string)
TypeError: initial_value must be str or None, not list
192.168.0.103 - - [13/Jan/2019 20:29:33] "PROPFIND /user/calendars/ HTTP/1.1" 500 59
```

If instead connecting with http://192.168.0.111:8080/dav or http://192.168.0.111:8080/dav/user the exception is thrown at a later stage, when "saving" the account in DAVx. It is still the same exception as previously shown. I do not believe that I've had trouble with DAVx in companion with Xandikos before.

**Comment by jelmer** [comment]
Ah, this is a regression in master. I'll try to push a fix this weekend.

**Comment by tusj** [comment]
Thanks for the fix! When connecting with DAVx, DAVx is unable to find the default calendar when redoing steps 1 and 2 above. That gives a warning from xandikos:
```
WARNING:root:Client requested unknown property {http://calendarserver.org/ns/}source
```
Creating a calendar from DAVx works though. I don't know if this is relevant, but the `.xandikos` file for the calendar created with `--defaults` has a content of
```
[DEFAULT]
type = calendar
```
whereas for the calendar created with DAVx the content is
```
[DEFAULT]
displayname = test
```

When refreshing the view with DAVx, none of the calendars remain visible.

There seems to be some 404's from Xandikos:
```
WARNING:root:Client requested unknown property {http://calendarserver.org/ns/}source
WARNING:root:Client requested unknown property {http://calendarserver.org/ns/}source
WARNING:root:Client requested unknown property {http://calendarserver.org/ns/}source
OUT: <ns0:multistatus xmlns:ns0="DAV:" xmlns:ns1="urn:ietf:params:xml:ns:carddav" xmlns:ns2="urn:ietf:params:xml:ns:caldav" xmlns:ns3="http://apple.com/ns/ical/" xmlns:ns4="http://calendarserver.org/ns/"><ns0:response><ns0:href>/user/calendars/</ns0:href><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype><ns0:current-user-privilege-set><ns0:privilege><ns0:all /></ns0:privilege></ns0:current-user-privilege-set><ns0:displayname>calendars</ns0:displayname></ns0:prop></ns0:propstat><ns0:propstat><ns0:status>HTTP/1.1 404 Not Found</ns0:status><ns0:prop><ns1:addressbook-description /><ns1:supported-address-data /><ns2:calendar-description /><ns3:calendar-color /><ns2:supported-calendar-component-set /><ns4:source /></ns0:prop></ns0:propstat></ns0:response><ns0:response><ns0:href>/user/calendars/0f44b2bd-bf5d-4340-bea9-b41d65ef7fd4/</ns0:href><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype><ns0:current-user-privilege-set><ns0:privilege><ns0:all /></ns0:privilege></ns0:current-user-privilege-set><ns0:displayname>0f44b2bd-bf5d-4340-bea9-b41d65ef7fd4</ns0:displayname></ns0:prop></ns0:propstat><ns0:propstat><ns0:status>HTTP/1.1 404 Not Found</ns0:status><ns0:prop><ns1:addressbook-description /><ns1:supported-address-data /><ns2:calendar-description /><ns3:calendar-color /><ns2:supported-calendar-component-set /><ns4:source /></ns0:prop></ns0:propstat></ns0:response><ns0:response><ns0:href>/user/calendars/calendar/</ns0:href><ns0:propstat><ns0:status>HTTP/1.1 200 OK</ns0:status><ns0:prop><ns0:resourcetype><ns0:collection /></ns0:resourcetype><ns0:current-user-privilege-set><ns0:privilege><ns0:all /></ns0:privilege></ns0:current-user-privilege-set><ns0:displayname>calendar</ns0:displayname></ns0:prop></ns0:propstat><ns0:propstat><ns0:status>HTTP/1.1 404 Not Found</ns0:status><ns0:prop><ns1:addressbook-description /><ns1:supported-address-data /><ns2:calendar-description /><ns3:calendar-color /><ns2:supported-calendar-component-set /><ns4:source /></ns0:prop></ns0:propstat></ns0:response></ns0:multistatus>
192.168.0.103 - - [14/Jan/2019 10:13:36] "PROPFIND /user/calendars/ HTTP/1.1" 207 2161
```

**Comment by jelmer** [comment]
should really be fixed now - sorry about that.

This highlights xandikos needs some unit test improvements :-/

**Comment by tusj** [comment]
Thanks! Everything seems to be working now :)
